dist: trusty
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt .
  - python -m nltk.downloader "punkt"
  - python -m nltk.downloader "averaged_perceptron_tagger"
  - python -m nltk.downloader "maxent_ne_chunker"
  - python -m nltk.downloader "words"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pip install coverage
  - coverage run setup.py test
