dist: trusty
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt .
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pip install coverage
  - coverage run setup.py test
